import math
from numpy import sqrt

AXES_WIDTH = 1

DISTANCE_BETWEEN_POINT = 1
POINT_RADIUS = 2

BLACK = (0, 0, 0)
GRAY = (150, 150, 150)
DARK_GRAY = (100, 100, 100)

BACKGROUND_COLOR = GRAY

COLOR_AXES = DARK_GRAY
COLOR_LINE = BLACK

PROPORTION_ORIGINAL_DRAWING = 1/3

## Value relative to the size of the original drawing window
INPUT_SAMPLING_BOX_PADDING_TOP = 1/10
INPUT_SAMPLING_BOX_PADDING_RIGHT = 1/10
INPUT_SAMPLING_BOX_HEIGHT = 1/5
INPUT_SAMPLING_BOX_WIDTH = 1/5

BOX_BORDER_WIDTH = 2
BOX_BORDER_COLOR = BLACK