#!/usr/bin/env python3
"""Module proposant les constantes nécessaire à pour le projet pao-dessine-moi-un-elephant"""

AXES_WIDTH = 1

DISTANCE_BETWEEN_POINT = 1
POINT_RADIUS = 2

BLACK = (0, 0, 0)
GRAY = (150, 150, 150)
DARK_GRAY = (100, 100, 100)
DARK_GREEN = (0, 50, 0)

SLIDER_HANDLE_COLOR = DARK_GREEN
SLIDER_COLOR = DARK_GRAY

BACKGROUND_COLOR = GRAY

COLOR_AXES = DARK_GRAY
COLOR_LINE = BLACK

PROPORTION_ORIGINAL_DRAWING = 1/3

DRAWING_RECT_BORDER_COLOR = DARK_GRAY
DRAWING_RECT_BORDER_WIDTH = 1

## Value relative to the size of the original drawing window
INPUT_SAMPLING_BOX_PADDING_TOP = 1/10
INPUT_SAMPLING_BOX_PADDING_RIGHT = 1/10
INPUT_SAMPLING_BOX_HEIGHT = 1/5
INPUT_SAMPLING_BOX_WIDTH = 1/5

BOX_BORDER_WIDTH = 2
BOX_BORDER_COLOR = DARK_GRAY
BOX_BORDER_COLOR_ON_FOCUS = BLACK

MIN_CIRCLE = 2
MAX_CIRCLE = 50

PROPORTION_VIRTUAL_KEYBOARD_HEIGHT = 1/2
